#!/bin/bash
name="Mash's Musings"
webdir="$PWD"
website="https://mashsmusings.neocities.org/" # Keep a trailing slash.
css="/style.css"
blogfile="index.html"
rssfile="rss.xml"
archivefile="$webdir/posts/.htaccess"
[ -z "$EDITOR" ] && EDITOR="vim"

[ ! -d "$webdir/posts/.drafts" ] &&
read -erp "Initialize blog in $webdir?" ask &&
	if [ "$ask" = "y" ]; then
	printf "Initializing blog system...\\n"
	mkdir -pv "$webdir/posts/.drafts" || printf "Error. Do you have write permissions in this directory?\\n"
	echo "Options +Indexes" > "$archivefile"
else
	exit
fi

newpost() { read -erp "Give a title for your post:
	" title
	echo "$title" | grep -q "\"" && printf "Double quotation marks (\") are not allowed in entry titles.\\n" && exit
	url="$(echo "$title" | iconv -c -f UTF-8 -t ASCII//TRANSLIT | tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed "s/-\+/-/g;s/\(^-\|-\$\)//g")"
	echo "AddDescription \"$title\" \"$url.html\"" >>  "$archivefile"|| { echo "Error: Is $archivefile writeable?"; exit; }
	( [ -f "$webdir/posts/.drafts/$url.html" ] || [ -f "$webdir/posts/$url.html" ] ) && echo "There is already an existing draft or post of that same name/URL." && exit
	$EDITOR "$webdir/posts/.drafts/$url.html" ;}

listandReturn() {
	printf "Listing contents of %s\\n" "$1"
	case "$(ls "$1" | wc -l)" in
		0) echo "There's nothing to $2." && exit 1 ;;
		1) number=1 && printf "There's only one entry to %s.\\nDefaulting selection to %s\\n" "$2" "$(ls -rc "$1" | awk -F '/' '{print $NF}')" ;;
		*) ls -rc "$1" | awk -F '/' '{print $NF}' | nl
                read -erp "Pick an entry by number to $2, or press Ctrl-C to cancel. " number ;;
	esac
	chosen="$(ls -rc "$1" | nl | grep -w " $number" | awk '{print $2}')"
	basefile="$(basename "$chosen")" && base="${basefile%.*}"
}

publish() { \
	delete draft
	htaccessentry=$(grep "$basefile" "$archivefile")
	realname="$(echo "$htaccessentry" | cut -d'"' -f2)"
	rssdate="$(grep "$basefile" posts/.htaccess | sed "s/.*\.html\"* *#*//g" | tr -d '\n')"
	[ -z "$rssdate" ] && rssdate="$(LC_TIME=en_US date '+%a, %d %b %Y %H:%M:%S %z')" # RSS date formats must comply with standards to validate.
	webdate="$(date '+%b. %-d, %Y')" # But this visible date you can set to any format.
	tmpdir=$(mktemp -d)

  printf "$(cat $webdir/posts/.blogtemplate)" "$realname" "$basefile" "$realname" "$webdate" "$(cat "$webdir/posts/.drafts/$basefile")" > "$webdir/posts/$basefile"
	printf "\\n<item>\\n<title>%s</title>\\n<guid>%s%s#%s</guid>\\n<pubDate>%s</pubDate>\\n<description><![CDATA[\\n%s\\n]]></description>\\n</item>\\n\\n" "$realname" "$website" "$blogfile" "$base" "$rssdate" "$(cat "$webdir/posts/.drafts/$basefile")" > "$tmpdir/rss"
	printf "<hr/>\\n<div class='post'>\\n<h1><a href='/posts/%s'>%s</a></h1>\\n<h4>Published %s</h4>\\n%s</div>\\n" "$basefile" "$realname" "$webdate" "$(cat "$webdir/posts/.drafts/$basefile")" > "$tmpdir/html"
	sed -i '' "/<\!-- LB -->/ r $tmpdir/html" "$blogfile"
	sed -i '' "/<\!-- LB -->/ r $tmpdir/rss" "$rssfile"
	sed -i '' "/ \"$base.html\"/ d" "$archivefile"
	echo "AddDescription \"$realname\" \"$basefile\" #$rssdate" >> "$archivefile"
	rm -f "$webdir/posts/.drafts/$chosen"
}

confirm() { read -erp "Really $1 \"$base\"? (y/N) " choice && echo "$choice" | grep -qi "^y$" || exit 1 ;}

delete() { \
  # loop through item tags and delete around tag containing $base guid
	sed -i '' '
  /<item/ {
    :next
    N
    /<\/item>/ !b next
  }
  /#"$base"<\/guid/ d
  ' "$rssfile"

  # loop through div tags and delete around tag containing $base
  sed -i '' '
  /<div class='post'>/ {
    :next
    N
    /<\/div>/ !b next
  }
  /"$base"/ d
  ' "$blogfile"

	rm -f "$webdir/posts/$basefile" && [[ "$1" != "draft" ]] && printf "Old blog entry removed.\\n";}

revise() { awk '/<div id="post"/{flag=1;next}/<\/body>/{flag=0}flag' "$webdir/posts/$chosen" > "$webdir/posts/.drafts/$basefile"
	"$EDITOR" "$webdir/posts/.drafts/$basefile"
	printf "Revision stored in posts/.drafts. Publish as normal entry when desired.\\n" ;}

case "$1" in
	n*) newpost ;;
	e*) listandReturn "$webdir"/posts/.drafts/ edit && "$EDITOR" "$webdir/posts/.drafts/$chosen" ;;
	p*) listandReturn "$webdir"/posts/.drafts/ publish && publish ;;
	t*) listandReturn "$webdir"/posts/.drafts/ trash && confirm trash && rm -f "$webdir/posts/.drafts/$chosen" && sed -i "/ \"$base.html\"/d" "$archivefile" ; printf "Draft deleted.\\n" ;;
	d*) listandReturn "$webdir"/posts/ delete && confirm delete && delete && sed -i "/ \"$base.html\"/d" "$archivefile" ;;
	r*) listandReturn "$webdir"/posts/ revise && revise ;;
  b*) ./books/.read_booklist.awk books/.booklist >books/index.html && echo "books/index.html updated";;
	*) printf "lb blog system by Luke Smith <luke@lukesmith.xyz>\\nUsage:\\n  lb n:\\tnew draft\\n  lb e:\\tedit draft\\n  lb p:\\tpublish/finalize draft\\n  lb r:\\trevise published entry\\n  lb t:\\tdiscard draft\\n  lb d:\\tdelete published entry\\n  lb b:\\tgenerate static books index.html\\n\\nBe sure to have the following pattern added to your RSS feed, blog file and blog index:\\n\\n<\!-- LB -->\\n\\nNew content will be added directly below that sequence. This is required.\\nSee https://github.com/LukeSmithxyz/lb for more.\\n" ;;
esac
